name: mobile_scanner_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  mobile_scanner: ^7.1.3
  nsd: ^4.0.3
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
